JwtToken:
    key: JWT_SECRET_KEY
server:
    port: 8011
spring:
    application:
        name: webapp
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: tung@172
        url: jdbc:mysql://localhost:3306/warehouse_manager
        username: root
    jpa:
        hibernate:
            ddl-auto: update
            naming:
                implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
            hibernate:
                enable_lazy_load_no_trans: true
                format_sql: true
                show_sql: true
        show-sql: true
    servlet:
        multipart:
            enabled: true
            max-file-size: 50MB
            max-request-size: 50MB
logging:
    level:
        root: DEBUG
